apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: infra-keycloak
  annotations:
    cert-manager.io/cluster-issuer: "infra-lets-encrypt-cluster-issuer-staging"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - staging-keycloak.saharaai.io
      secretName: keycloak-cert
  rules:
    - host: staging-keycloak.saharaai.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: application
                port:
                  number: 8080